version: "3"
services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:prototype-japanese-8
    volumes:
      - ./meili_data:/meili_data
    environment: 
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
    ports:
      - 7700:7700
    restart: always
volumes:
  meili-data:
    driver: local